/**
 * @description     call back class to implement Metadata.DeployCallBack
 * @author          Mark Meyer
 * @date            09/27/2024
 */
public class MyDeployCallback implements Metadata.DeployCallback {

    /**
     * @description empty method in order to instantiate class
     * @param result
     * @param context
     */
    public void handleResult(Metadata.DeployResult result,
                             Metadata.DeployCallbackContext context) {
        
    }
}